# -*- coding: utf-8 -*-
"""1_úkol

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_-qN-OUekB9DET14Aqr7oIOvXOtVT9ry
"""

import sys

USERS = {
    "bob": "123",
    "ann": "pass123",
    "mike": "password123",
    "liz": "pass123"
}

TEXTS = [
    """
Situated about 10 miles west of Kemmerer,
Fossil Butte is a ruggedly impressive
topographic feature that rises sharply
some 1000 feet above Twin Creek Valley
to an elevation of more than 7500 feet
above sea level. The butte is located just
north of US 30 and the Union Pacific Railroad,
which traverse the valley.
""",
    """
At the base of Fossil Butte are the bright
red, purple, yellow and gray beds of the Wasatch
Formation. Eroded portions of these horizontal
beds slope gradually upward from the valley floor
and steepen abruptly. Overlying them and extending
to the top of the butte are the much steeper
buff-to-white beds of the Green River Formation,
which are about 300 feet thick.
""",
    """
The monument contains 8198 acres and protects
a portion of the largest deposit of freshwater fish
fossils in the world. The richest fossil fish deposits
are found in multiple limestone layers, which lie some
100 feet below the top of the butte. The fossils
represent several varieties of perch, as well as
other freshwater genera and herring similar to those
in modern oceans. Other fish such as paddlefish,
garpike and stingray are also present.
"""
]


def login():
    """Zpracuje přihlášení uživatele a zkontroluje správnost údajů."""
    username = input("username: ")
    password = input("password: ")

    if USERS.get(username) == password:
        print("-" * 40)
        print(f"Welcome to the app, {username}")
        print(f"We have {len(TEXTS)} texts to be analyzed.")
        print("-" * 40)
    else:
        print("unregistered user, terminating the program..")
        sys.exit()


def select_text():
    """Zpracuje výběr textu od uživatele."""
    try:
        selection = int(input(f"Enter a number btw. 1 and {len(TEXTS)} to select: "))
        if 1 <= selection <= len(TEXTS):
            return TEXTS[selection - 1]
        else:
            print("Invalid text number, terminating the program..")
            sys.exit()
    except ValueError:
        print("Invalid input, terminating the program..")
        sys.exit()


def analyze_text(text):
    """Analyzuje vybraný text a vypíše statistiky."""
    words = text.split()
    clean_words = [word.strip(".,:;!?") for word in words]

    # Vypočítá statistiky
    word_count = len(clean_words)
    titlecase_count = sum(1 for word in clean_words if word.istitle())
    uppercase_count = sum(1 for word in clean_words if word.isupper())
    lowercase_count = sum(1 for word in clean_words if word.islower())
    numeric_count = sum(1 for word in clean_words if word.isnumeric())
    numeric_sum = sum(int(word) for word in clean_words if word.isnumeric())

    print("-" * 40)
    print(f"There are {word_count} words in the selected text.")
    print(f"There are {titlecase_count} titlecase words.")
    print(f"There are {uppercase_count} uppercase words.")
    print(f"There are {lowercase_count} lowercase words.")
    print(f"There are {numeric_count} numeric strings.")
    print(f"The sum of all the numbers {numeric_sum}")
    print("-" * 40)

    # Vytvoří a vypíše sloupcový graf
    print("LEN|  OCCURRENCES  |NR.")
    print("-" * 40)

    word_lengths = {}
    for word in clean_words:
        length = len(word)
        word_lengths[length] = word_lengths.get(length, 0) + 1

    sorted_lengths = sorted(word_lengths.keys())

    for length in sorted_lengths:
        count = word_lengths[length]
        bar = "*" * count
        print(f"{length:3}|{bar:<15}|{count}")


def main():
    """Hlavní funkce programu."""
    login()
    selected_text = select_text()
    analyze_text(selected_text)


if __name__ == "__main__":
    main()